# ECM1416: Computational Mathematics
## Worksheet #2: Matrix inverse


In [1]:
# import the numpy package in the np namespace
import numpy as np

# this line will load the plotting function into the namespace plt.
import matplotlib.pyplot as plt

# the following lines prevent Python from opening new windows for figures. 
%matplotlib inline

### Linear algebra functions in numpy
Many linear algebra functions in Numpy are stored in the <tt>numpy.linalg</tt> namespace: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

For example, the determinant of a matrix can be calculated using <tt>numpy.linalg.det()</tt>, and the inverse using <tt>numpy.linalg.inv()</tt>

## Exercises
### Exercise 1: Determinant
The aim of this exercise is to code a function implementing the Laplace formula for calculating the determinant. You are recommended to use subfunctions for calculating the minors and cofactors (you will need them later). 
Compare your function to Numpy's determinant function on a couple of matrices. 


In [46]:
def minors(matrix):
    '''
    Calculates the matrix of minors for the input matrix

    Return:
    A matrix of matrices where each sub matrix is the minor
    '''
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    if rows == 1 and cols == 1:
        return matrix[0, 0]
    minor_matrix = np.zeros((rows, cols, rows-1, cols-1))
    row_delta = 0
    col_delta = 0
    for i in range(rows):
        for j in range(cols):
            for k in range(rows):
                if k > i:
                    row_delta = -1
                for l in range(cols):
                    if l > j:
                        col_delta = -1   
                    if l != j and k != i: 
                        minor_matrix[i, j, k + row_delta, l + col_delta] = matrix[k, l]
                
                row_delta = 0
                col_delta = 0
                        
    return minor_matrix


def determinant(matrix):
    '''
    Calculates the determinant of the input matrix   

    Returns:
    The determinant value 
    '''
    if matrix.shape == (2, 2):
        ad = matrix[0, 0] * matrix[1, 1]
        cb = matrix[0, 1] * matrix[1, 0]
        return ad-cb

    minor = minors(matrix)
    det = 0
    for i in range(matrix.shape[1]):
        det += ((-1)**i)*determinant(minor[0, i])*matrix[0, i]

    return det


a = np.matrix([[1, 5, 7], 
               [11, -9, 1], 
               [2, -3, -1]])
print(a.shape)
b = minors(a)
print(determinant(a))

(3, 3)
-28.0


### Exercise 2: Inverse
Build on the code you wrote for part one to provide the Cramer's rule solution to calculate the inverse of a matrix (as discussed in the lecture). Again compare your approach to numpy's results on some matrices. 

In [54]:
def cofactors(matrix):
    '''
    Calculates the cofactors for the matrix

    Returns:
    Matrix containing the determinant of each minor with the correct sign
    '''
    minor_matrix = minors(matrix)
    rows = minor_matrix.shape[0]
    cols = minor_matrix.shape[1]
    cofactor_matrix = np.asmatrix(np.zeros(matrix.shape))

    for i in range(rows):
        for j in range(cols):
            cofactor_matrix[i, j] = ((-1)**(i+j))*determinant(minor_matrix[i, j])

    return cofactor_matrix

def transpose(matrix):
    '''
    Transposes the matrix

    Returns:
    The transpose of the input matrix
    '''
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    transposed = np.asmatrix(np.zeros((cols, rows)))

    for i in range(rows):
        for j in range(cols):
            transposed[j, i] = matrix[i, j]

    return transposed


def inverse(matrix):
    '''
    Calculates the inverse of the matrix

    Returns:
    The inverse matrix
    '''
    det = determinant(matrix)
    if det == 0:
        raise ValueError("determinant of input matrix is 0, no inverse exists")
    cofact = cofactors(matrix)
    return (1/det)*transpose(cofact)

c = inverse(a)
print(c)
print(inverse(c)*c)


[[-0.42857143  0.57142857 -2.42857143]
 [-0.46428571  0.53571429 -2.71428571]
 [ 0.53571429 -0.46428571  2.28571429]]
[[ 1.00000000e+00  1.54638207e-15 -8.50113630e-15]
 [-9.43689571e-16  1.00000000e+00  4.44089210e-16]
 [-5.55111512e-17  5.55111512e-17  1.00000000e+00]]


### Exercise 3: System of linear equations
The aim of this exercise is to use the inverse to solve a system of linear equations. To this end, let's look at a small problem: 
1. On Monday, you went to the shop and bought 2 coffees, one tea and 5 donuts (generous of you) and paid 12 pounds. 
2. On Tuesday, you went again and bought 3 coffees and 6 donuts and pay 13.50. 
3. Finally on Wednesday, you bought 1 coffee, 1 tea and two donuts and pay 6.50. 

Question: what is the price of each of the items you bought this week? 

Model this as a system of linear equation and solve it using the inverse. 

In [1]:
system = np.asmatrix([[2, 1, 5], 
                     [3, 0, 6],
                     [1, 1, 2]])
prices = np.asmatrix([[12],
                     [13.5],
                     [6.5]])

solutions = inverse(system)*prices

print(f"Price of a coffee: £{solutions[0, 0]}")
print(f"Price of a tea: £{solutions[1, 0]}")
print(f"Price of a donut: £{solutions[2, 0]}")


NameError: name 'np' is not defined